name: Bundle tests

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: backend security
        run: bundle exec bundle audit
      - name: Run leak update and Make sure memory leaks are not in your gem dependencies
        run: bundle exec bundle leak check --update
